name: HTML5 Validator

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HTML5 Validation Check
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: recipes/